apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx               # Example: nginx container
        volumeMounts:
        - name: storage-volume
          mountPath: /data         # Mount PVC at /data inside container
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: my-pvc      # Reference the PVC created earlier
